<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('7', '/uploads/allimg/150328/1-15032Q13451423.jpg');
$maNum = 1;
$myaddons[$maNum] = array('8', '/uploads/allimg/150328/1-15032Q13513V2.jpg');
$maNum = 2;
$myaddons[$maNum] = array('9', '/uploads/allimg/150328/1-15032QG610539.jpg');
$maNum = 3;
$myaddons[$maNum] = array('10', '/uploads/allimg/150328/1-15032QG62K39.jpg');
$maNum = 4;
