<?php
$z[0]=Array("global","",410,439);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",501,530);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",608,637);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",711,740);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("include","",811,846);
$z[4][4]['filename']="head.htm";
$z[5]=Array("feedback","   \r\n　　<li><small><a href=\"#\">[field:useame function=\"(@me=='guest' ? '游客' : @me)\"/]</a> 评论 <a href=\"[field:global.cfg_phpurl/]/feedback.php?aid=[field:aid/]\">[field:title/]</a></small>[field:msg/]</li> \r\n　　",1293,1594);
$z[5][4]['row']="10";
$z[5][4]['titlelen']="30";
$z[5][4]['infolen']="60";
$z[5][4]['typeid']="8";
$z[6]=Array("arclist","\r\n	    	<li><span class=\"dot\">·</span> <a title=\"[field:title/]\" href=\"[field:arcurl/]\">[field:title/]</a><em class=\"date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</em></li>\r\n			",2144,2386);
$z[6][4]['typeid']="4";
$z[6][4]['titlelen']="20";
$z[6][4]['row']="8";
$z[7]=Array("channel","\r\n    		   <li>\r\n    		   <a href=\"[field:typeurl/]\"><span>[field:typename/]</span></a>\r\n    		   </li>\r\n			   ",3071,3222);
$z[7][4]['type']="son";
$z[8]=Array("include","",3363,3400);
$z[8][4]['filename']="footer.htm";

?>