<?php
$z[0]=Array("global","",410,439);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",501,530);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",608,637);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",711,740);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("include","",812,847);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1361,1382);
$z[5][4]['name']="content";
$z[6]=Array("arclist","\r\n        <li><span class=\"dot\">·</span> <a title=\"[field:title/]\" href=\"[field:arcurl/]\">[field:title/]</a><em class=\"date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</em></li>\r\n      ",1990,2237);
$z[6][4]['typeid']="4";
$z[6][4]['titlelen']="20";
$z[6][4]['row']="8";
$z[7]=Array("include","",3316,3353);
$z[7][4]['filename']="footer.htm";

?>