<?php
$z[0]=Array("global","",412,441);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",503,532);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",610,639);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",713,742);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("include","",814,849);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","\r\n        <li><span class=\"dot\">·</span> <a title=\"[field:title/]\" href=\"[field:arcurl/]\">[field:title/]</a><em class=\"date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</em></li>\r\n      ",6557,6804);
$z[5][4]['typeid']="4";
$z[5][4]['titlelen']="20";
$z[5][4]['row']="8";
$z[6]=Array("channel","\r\n           <li>\r\n           <a href=\"[field:typeurl/]\"><span>[field:typename/]</span></a>\r\n           </li>\r\n         ",7516,7676);
$z[6][4]['type']="son";
$z[7]=Array("include","",7821,7858);
$z[7][4]['filename']="footer.htm";

?>