<?php
$z[0]=Array("global","",567,596);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",657,686);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",764,793);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",867,896);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("include","",959,994);
$z[4][4]['filename']="head.htm";
$z[5]=Array("global","",1107,1136);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",1897,1926);
$z[6][4]['name']="cfg_templeturl";
$z[7]=Array("global","",2782,2811);
$z[7][4]['name']="cfg_templeturl";
$z[8]=Array("arclist","\r\n				<td>\r\n				<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n				<img src=\"[field:litpic/]\" width=\"167\" height=\"125\" alt=\"[field:title/]\"/><br><span>[field:title/]</span>\r\n				</a></li>\r\n				</td>\r\n				",3222,3508);
$z[8][4]['row']="8";
$z[8][4]['typeid']="11";
$z[8][4]['type']="image.";
$z[8][4]['titlelen']="26";
$z[9]=Array("arclist","\r\n	    	<li><span class=\"dot\">·</span> <a title=\"[field:title/]\" href=\"[field:arcurl/]\">[field:title/]</a><em class=\"date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</em></li>\r\n			",5119,5361);
$z[9][4]['typeid']="4";
$z[9][4]['titlelen']="20";
$z[9][4]['row']="8";
$z[10]=Array("include","",6438,6475);
$z[10][4]['filename']="footer.htm";

?>