<?php
$z[0]=Array("global","",589,618);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",679,708);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",786,815);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",889,918);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("include","",981,1016);
$z[4][4]['filename']="head.htm";
$z[5]=Array("global","",1129,1158);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",1919,1948);
$z[6][4]['name']="cfg_templeturl";
$z[7]=Array("global","",3468,3497);
$z[7][4]['name']="cfg_templeturl";
$z[8]=Array("arclist","\r\n				<td>\r\n				<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n				<img src=\"[field:litpic/]\" width=\"167\" height=\"125\" alt=\"[field:title/]\"/><br><span>[field:title/]</span>\r\n				</a></li>\r\n				</td>\r\n				",3908,4194);
$z[8][4]['row']="8";
$z[8][4]['typeid']="11";
$z[8][4]['type']="image.";
$z[8][4]['titlelen']="26";
$z[9]=Array("arclist","\r\n	    	<li><span class=\"dot\">·</span> <a title=\"[field:title/]\" href=\"[field:arcurl/]\">[field:title/]</a><em class=\"date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</em></li>\r\n			",5805,6047);
$z[9][4]['typeid']="4";
$z[9][4]['titlelen']="20";
$z[9][4]['row']="8";
$z[10]=Array("include","",7096,7133);
$z[10][4]['filename']="footer.htm";

?>