<?php
$z[0]=Array("global","",469,498);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",560,589);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",667,696);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",770,799);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("include","",868,903);
$z[4][4]['filename']="head.htm";
$z[5]=Array("list","\r\n						<li>\r\n							<div class=\"thumb\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" /></a></div>\r\n							<div class=\"des\">\r\n								<p class=\"default\"><a href=\"[field:arcurl/]\">[field:title/]</a></p>\r\n\r\n								<p class=\"default catalog\">分类:[field:typelink/]</p>\r\n							</div>\r\n						</li>\r\n					",1315,1720);
$z[5][4]['pagesize']="16";
$z[5][4]['type']="image.";
$z[6]=Array("arclist","\r\n	    	<li><span class=\"dot\">·</span> <a title=\"[field:title/]\" href=\"[field:arcurl/]\">[field:title/]</a><em class=\"date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</em></li>\r\n			",2287,2529);
$z[6][4]['typeid']="4";
$z[6][4]['titlelen']="20";
$z[6][4]['row']="8";
$z[7]=Array("include","",3597,3634);
$z[7][4]['filename']="footer.htm";

?>