<?php
$z[0]=Array("global","",456,485);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",547,576);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",654,683);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",757,786);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("include","",855,890);
$z[4][4]['filename']="head.htm";
$z[5]=Array("list","\r\n							<tr>\r\n							<td class=\"title\"><span class=\"catalog\">[ [field:typelink/] ]</span> <a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\"><span class=\"style1\">[field:title/]</span></a></td>\r\n							<td>2012-06-11</td>\r\n						    </tr>\r\n						 ",1478,1776);
$z[5][4]['pagesize']="20";
$z[6]=Array("pagelist","",1885,1963);
$z[6][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[6][4]['listsize']="5";
$z[7]=Array("arclist","\r\n	    	<li><span class=\"dot\">·</span> <a title=\"[field:title/]\" href=\"[field:arcurl/]\">[field:title/]</a><em class=\"date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</em></li>\r\n			",2539,2781);
$z[7][4]['typeid']="4";
$z[7][4]['titlelen']="20";
$z[7][4]['row']="8";
$z[8]=Array("include","",3849,3886);
$z[8][4]['filename']="footer.htm";

?>